3663: Updating UT for chassis under svc-system
tamanna-k/ODIM pull request #2
Opened 2020-10-28 03:46 UTC by tamanna-k

updating UT for chassis under svc-system for Network Adapters collection and individual Network Adapter

2020-10-28 03:49 UTC, jeevan-kamkar requested changes
address the requested changes

2020-10-28 03:49 UTC, jeevan-kamkar commented on svc-systems/chassis/getresource_test.go
> +			name: "successful get data",
rename the test case

2020-10-28 03:49 UTC, jeevan-kamkar commented on svc-systems/chassis/getresource_test.go
> +			name: "successful get data",
rename the test case

2020-10-28 03:54 UTC, jeevan-kamkar approved these changes
LGTM

2020-10-29 05:50 UTC, Bharath-KKB approved these changes

2020-10-29 05:51 UTC, merged