Odim 3696: removing iLO reference from 'Code' parameter
tamanna-k/ODIM pull request #6
Opened 2020-11-10 10:47 UTC by tamanna-k

2020-11-10 13:12 UTC, jeevan-kamkar approved these changes

2020-11-10 14:45 UTC, Bharath-KKB commented on plugin-redfish/rfpresponse/errorResponse.go
>  				MsgExtendedInfo{
There is no Base.1.0.Failed in the registry

2020-11-10 14:47 UTC, Bharath-KKB commented on plugin-redfish/rfpresponse/errorResponse.go
ErrorResopnse ??

2020-11-10 14:55 UTC, Bharath-KKB requested changes
I see a lot of instances where issues raised by Robert are there in this file. Fix all such issues

2020-11-12 13:38 UTC, Bharath-KKB approved these changes

2020-11-13 06:27 UTC, merged